version: '3.7'

services:

  ptm-be:
    build:
      context: .
      dockerfile: ./ptm-be/Dockerfile
    image: ptm-be:latest
    container_name: ptm-be-compose-main  
    network_mode: "host"
    tty: true 
    
  ptm-fe:   
    build:
      context: .
      dockerfile: ./ptm-fe/Dockerfile
    image: ptm-fe:latest
    volumes:
      - '.:/app'
      - '/app/node_modules'   
    environment:
      - CHOKIDAR_USEPOLLING=true
    container_name: ptm-fe-compose-main   
    network_mode: "host"
    tty: true   


