version: '3.7'

services: 
  ptm-fe:   
    build:
      context: .
      dockerfile: Dockerfile
    image: ptm-fe:latest
    volumes:
      - '.:/app'
      - '/app/node_modules'   
    environment:
      - CHOKIDAR_USEPOLLING=true
    container_name: ptm-fe-compose   
    network_mode: "host"
    tty: true   

